# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190314_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('referprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoryid', models.IntegerField(null=True)),
                ('desc', models.CharField(max_length=200)),
                ('pic', models.CharField(max_length=200)),
            ],
        ),
    ]
