# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_goods'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
    ]
