# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-16 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_ordergoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
