# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190316_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
